const classes = [];
const types = [];
const vbaCodeDiv = document.getElementById('vbaCode');
const classListDiv = document.getElementById('classList');

// Format input string to capitalize the first letter of each word
function formatString(input) {
    input = input.toLowerCase();
    return input
        .split(' ') // Split the string by spaces
        .map(word => word.charAt(0).toUpperCase() + word.slice(1)) // Capitalize the first letter of each word
        .join(''); // Join the words without spaces
}

// Add class on button click
document.getElementById('addClassButton').addEventListener('click', () => {
    const input = document.getElementById('className').value.trim();
    const selectedType = document.getElementById('varType').value;
    if (input) {
        const baseName = formatString(input);
        if (!classes.includes(baseName)) {
            classes.push(baseName);
            types.push(selectedType); // Store the selected type
            updateClassList();
            document.getElementById('className').value = '';
            generateVbaCode();
        }
    }
});

// Reset button functionality
document.getElementById('resetButton').addEventListener('click', () => {
    classes.length = 0; // Clear classes array
    types.length = 0; // Clear types array
    updateClassList();
    vbaCodeDiv.textContent = ''; // Clear generated code
});

document.getElementById('copyButton').addEventListener('click', () => {
    navigator.clipboard.writeText(vbaCodeDiv.textContent)
        .then(() => {
            const copyButton = document.getElementById('copyButton');
            copyButton.textContent = "Copied";
            copyButton.style.backgroundColor = "green"; // Change background to green

            // Reset text and background after 5 seconds
            setTimeout(() => {
                copyButton.textContent = "Copy to Clipboard"; // Reset button text
                copyButton.style.backgroundColor = ""; // Reset background
            }, 5000);
        })
        .catch(err => {
            console.error("Failed to copy code: ", err); // Log error to console
        });
});
// Update the displayed class list
function updateClassList() {
    classListDiv.innerHTML = classes.map((className, index) => {
        return `<div>${capitalizeFirstLetter(className)} (${types[index]})</div>`;
    }).join('');
}

// Generate VBA code based on added classes
function generateVbaCode() {
    let vbaCode = "' ========================================================================\n";
    vbaCode += "' Automatically generated by VBA Class Generator\n";
    vbaCode += "' Programmer: \n";
    vbaCode += "' Date: \n";
    vbaCode += "' ========================================================================\n\n";

    classes.forEach((className, index) => {
        const formattedClassName = capitalizeFirstLetter(className);
        const variableType = types[index]; // Get the variable type for this class
        vbaCode += `Private p${formattedClassName} As ${variableType}\n`; // Include variable type
    });

    vbaCode += "\n\n";

    classes.forEach((className, index) => {
        const formattedClassName = capitalizeFirstLetter(className);
        vbaCode += `' Getter method for the ${formattedClassName} property\n`;
        vbaCode += `Public Property Get ${formattedClassName}() As ${types[index]}\n`; // Include return type
        vbaCode += `   ${formattedClassName} = p${formattedClassName}\n`;
        vbaCode += "End Property\n\n";

        vbaCode += `' Setter method for the ${formattedClassName} property\n`;
        vbaCode += `Public Property Let ${formattedClassName}(value As ${types[index]})\n`; // Include parameter type
        vbaCode += `   p${formattedClassName} = value\n`;
        vbaCode += "End Property\n\n";
    });

    vbaCode += "' PrintAll method to print each property\n";
    vbaCode += "Public Sub PrintAll()\n";
    vbaCode += '   Debug.Print "========================================"\n';
    classes.forEach((className, index) => {
        const formattedClassName = capitalizeFirstLetter(className);
        vbaCode += `   Debug.Print "${formattedClassName}: (" & p${formattedClassName} & ")"\n`;
    });
    vbaCode += '   Debug.Print "========================================"\n';
    vbaCode += "End Sub\n";

    vbaCodeDiv.textContent = vbaCode; // Update the displayed code
}

// Capitalize the first letter of a string
function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

// Add class on pressing Enter key
document.getElementById('className').addEventListener('keydown', (event) => {
    if (event.key === 'Enter') { // Check if the pressed key is Enter
        event.preventDefault(); // Prevent the default form submission
        document.getElementById('addClassButton').click(); // Simulate click on the Add Class button
    }
});
